version: "3"

####################################################################################################
# Creating container MySQL
# command: "--innodb_use_native_aio=0" this is required to mount the mysql volume on a windows 10 Home 
# edition machine running virtual box, not required for non windows based OS's  
####################################################################################################
services:
 
  mysql:

    image: mysql:5.7
    command: "--innodb_use_native_aio=0" # this is required to mount the mysql volume on a windows 10 Hoem edition machine running virtual box  
    ports:
        - "3306:3306"
    expose:
        - 3306
    volumes: 
      - ./image/mysql/data:/var/lib/mysql
        
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        

####################################################################################################
# Creating container PHP
####################################################################################################
  php:

    build: ./image/php/
    ports:
        - "9000:9000"
    volumes:
        - ./src/app/:/var/www/html
    links:
        - mysql
    
####################################################################################################
# Creating container (Nginx)
####################################################################################################
  nginx:

      image: nginx:latest
      ports:
          - 8080:80
      volumes:
          - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php